main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
	path('', views.product_list, name='product_list')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('main.urls', namespace='main'))
]

main/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
	name = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, unique=True)
	
	class Meta:
		ordering = ('name', )
		verbose_name = 'Категория'
		verbose_name_plural = 'Категории'

	def __str__(self):
		return self.name
	
class Product(models.Model):
	category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

	name = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, unique=True)
	image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
	description = models.TextField(blank=True)
	sailerName = models.CharField(max_length=100, db_index=True)
	sailerStatistics = models.DecimalField(max_digits=10, decimal_places=2)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	available = models.BooleanField(default=True)
	createdAt = models.DateTimeField(auto_now_add=True)
	updatedAt = models.DateTimeField(auto_now=True)

	class Meta: 
		ordering = ('name',)

	def __str__(self):
		return self.name

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.
def product_list(request, category_slug=None):
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)

	category = None
	if category_slug:
		category = get_object_or_404(Category, category_slug=category_slug)
		products = products.filter(category=category)

	return render(request, 'main/product/list.html', {
		'category': category,
		'categories': categories,
		'products': products
	})

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <a href="{% url 'main:product_list' %}">Лого</a>
    (Бейс) {% block content %}{% endblock content %}
  </body>
</html>

main/templates/main/product/list.html
{% extends "main/base.html" %} {% block title %}Продукты{% endblock title %}
{%block content %} Контенд страницы {% endblock content %}